language: python
python:
  - "3.3"
install: 
  - "pip install -r requirements-tests.txt --use-mirrors"
  - "pip install coveralls"
  - "python setup.py install"
script:
  nosetests --with-coverage --cover-package=ccr,ccrauth
after_success:
  - coveralls
  - coverage xml
  - python-codacy-coverage -r coverage.xml
