language: python
python:
  - "3.3"
install: 
  - "pip install -r requirements-tests.txt --use-mirrors"
  - "python setup.py install"
script: "nosetests --with-coverage --cover-package=ccr"
after_success: "coveralls"
